multicamera_node:
    ros__parameters:
        use_ros_time: false
        camera_settings:
            mode: 2
            fps: 20
            resolution: [640, 480]
            exposure: [480000, 400000000]
            gain: [1, 16]
            ae_lock: false
            awb_lock: true

        camera_names:
            - "front_left"
            - "front_right"
            - "side_right"
            - "side_left"
        camera_urls:
            - "package://argus_camera_ros/config/front_left_info.yaml"
            - "package://argus_camera_ros/config/front_right_info.yaml"
            - "package://argus_camera_ros/config/side_right_info.yaml"
            - "package://argus_camera_ros/config/side_left_info.yaml"
